# Generated by Django 4.2 on 2023-05-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_to_read',
        ),
    ]
